### PR TITLE
Clean up some code, fix some stuff (untested)

### PR DESCRIPTION
**Pull request by edwinfinch**
I see you love your comments :stuck_out_tongue: 

Just cleaned up some code, and now using struct instead of writing/reading bools independently for better efficiency and reliability. Removed all of that "static" crap, you don't need it unless it's for a buffer inside of a function.

### CODE REVIEW

**Comment by Aborgh** [comment]
Woooweeee! That's a lot of fixing! Thank you, and yeah I love my comments , it keeps me on track of what the function does. :P (The YouTube link I will keep ;)) The Bluetooth setting will not work by the way because I have yet to implemented it in the JavaScript, because I do not know how to add more than 1 setting! Will upload the html tonight also if you want to look at it?

Again thank you so freaking much!

**Comment by edwinfinch** [comment]
No problem! Glad you're this excited :) 

I'd be happy to look at the code again w/ HTML tonight/early tomorrow.

**Comment by Aborgh** [comment]
I tried to compile it but it says that settings is undeclared, I have added an index.html also to master branch :)

**Comment by edwinfinch** [comment]
Add:
Settings settings;

To the top of the file, that will fix that. I can look at the html when I'm
not mobile

**Comment by Aborgh** [comment]
Added Settings settings; at the top , did nothing though. I will make a much pretier version of the html on a later point but you get the idea :P

**Pull request merged**
